name    'jdowning/statsd'
version '1.1.0'
source 'https://github.com/justindowning/puppet-statsd'
author 'Justin Downing'
license 'Apache License, Version 2.0'
summary 'Install and manage statsd'
description 'Install and manage statsd'
project_page 'https://github.com/justindowning/puppet-statsd'
dependency 'puppetlabs/stdlib', '>=4.1.0'
